openapi: 3.0.3

info:
  title: Emd Core Services
  version: 1.0.0
  description: Emd Core microservice
  contact:
    name: PagoPA S.p.A.
    email: cstar@pagopa.it

servers:
  - description: Development Test
    url: https://api-io.dev.cstar.pagopa.it/emd
    x-internal: true
  - description: User Acceptance Test
    url: https://api-io.uat.cstar.pagopa.it/emd
    x-internal: true

tags:
  - name: submit
    description: Related to 'submit' operations
  - name: Payment
    description: Related to 'Payment' operations

paths:
  /message-core/sendMessage:
    parameters:
      - $ref: '#/components/parameters/RequestId'

    post:
      operationId: submitMessage
      description: Submit a message
      security:
        - bearerAuth: [ ]
      tags: [ submit ]
      requestBody:
        $ref: '#/components/requestBodies/SendMessage'
      responses:
        "200":
          #description: No channels enabled
          $ref: '#/components/responses/SendMessageResponse'
        "202":
          #description: Accepted
          $ref: '#/components/responses/SendMessageResponse'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many requests
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          description: Unexpected error
  /payment/retrievalTokens/{retrievalId}:
    get:
      tags:
        - Payment
      summary: >-
        ENG: Get retrieval payload - IT: Recupera il retrieval payload
      operationId: getRetrieval
      description: Get retrieval
      security:
        - bearerAuth: [ ]
      parameters:
        - name: Accept-Language
          in: header
          description: 'ENG: Language - IT: Lingua'
          schema:
            type: string
            pattern: "^[ -~]{2,5}$"
            minLength: 2
            maxLength: 5
            example: it-IT
            default: it-IT
          required: true
        - name: retrievalId
          in: path
          description: 'ENG: Unique ID that identify retrieval payload - IT: Identificativo univoco del retrieval payload'
          required: true
          schema:
            type: string
            description: 'ENG: Unique ID that identify retrieval payload - IT: Identificativo univoco del retrieval payload'
            pattern: "^[ -~]{1,50}$"
            minLength: 50
            maxLength: 50
            example: "0e4c6629-8753-234s-b0da-1f796999ec2-15038637960920"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrievalResponseDTO'
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrievalErrorDTO'
              example:
                code: BAD_REQUEST
                message: Bad request
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrievalErrorDTO'
              example:
                code: AUTHENTICATION_FAILED
                message: Something went wrong with authentication
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '404':
          description: The TPP was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrievalErrorDTO'
              example:
                code: RETRIEVAL_NOT_FOUND
                message: Retrieval does not exist or is not active
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrievalErrorDTO'
              example:
                code: TOO_MANY_REQUESTS
                message: Too many requests
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrievalErrorDTO'
              example:
                code: RETRIEVAL_GENERIC_ERROR
                message: Application error
          headers:
            Access-Control-Allow-Origin:
              description: Indicates whether the response can be shared with requesting code from the given origin
              required: false
              schema:
                $ref: '#/components/schemas/AccessControlAllowOrigin'
            RateLimit-Limit:
              description: The number of allowed requests in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitLimit'
            RateLimit-Reset:
              description: The number of seconds left in the current period
              required: false
              schema:
                $ref: '#/components/schemas/RateLimitReset'
            Retry-After:
              description: The number of seconds to wait before allowing a follow-up request
              required: false
              schema:
                $ref: '#/components/schemas/RetryAfter'
components:
  schemas:

    RetrievalErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - TPP_NOT_FOUND
            - RETRIEVAL_NOT_FOUND
            - AUTHENTICATION_FAILED
            - RETRIEVAL_GENERIC_ERROR
            - TOO_MANY_REQUESTS
            - BAD_REQUEST
          description: |-
            "ENG: Error code: TPP_NOT_FOUND: TPP does not exist or is not active,
             RETRIEVAL_NOT_FOUND: Retrieval does not exist or is not active,
             AUTHENTICATION_FAILED: Something went wrong with authentication,
             RETRIEVAL_GENERIC_ERROR: Application error,
             TOO_MANY_REQUESTS: Too many requests,
             BAD_REQUEST: Bad request - IT: Codice di errore:
             TPP_NOT_FOUND: La TPP non esiste o non è attiva, 
             RETRIEVAL_NOT_FOUND: Il retrieval non esiste o non è attivo,
             AUTHENTICATION_FAILED: Qualcosa è andato storto con l'autenticazione,
             RETRIEVAL_GENERIC_ERROR: Errore applicativo,
             TOO_MANY_REQUESTS: Troppe richieste,
             BAD_REQUEST: Request errata"
        message:
          type: string
          description: 'ENG: Error message - IT: Messaggio di errore'
          maxLength: 250
          pattern: "^[\\w\\s.,!?'\"-]+$"

    RetrievalResponseDTO:
      type: object
      required:
        - retrievalId
      description: "Retrieval Response information"
      properties:
        retrievalId:
          type: string
          description: 'ENG: Unique ID that identify retrieval payload - IT: Identificativo univoco del retrieval payload'
          pattern: "^[ -~]{1,50}$"
          minLength: 50
          maxLength: 50
          example: "0e4c6629-8753-234s-b0da-1f796999ec2-15038637960920"
        tppId:
          type: string
          description: 'ENG: Unique ID that identify TPP on PagoPA systems - IT: Identificativo univoco della TPP sui sistemi PagoPA'
          pattern: "^[ -~]{1,50}$"
          minLength: 50
          maxLength: 50
          example: "0e3bee29-8753-447c-b0da-1f7965558ec2-1706867960900"
        deeplink:
          type: string
          description: "Rappresenta il collegamento profondo (DeepLink) che consente il reindirizzamento diretto a una specifica sezione o funzionalità dell'app TPP. Deve essere una stringa alfanumerica che rispetti un formato specifico e avere una lunghezza compresa tra 48 e 128 caratteri."
          pattern: "^[a-zA-Z0-9._~:/?#\\[\\]@!$&'()*+,;=-]{48,128}$"
          minLength: 10
          maxLength: 128
          example: "https://example.com/deeplink/123e4567-e89b-12d3-a456-426614174000?userId=1234567890&session=abcdef"
        paymentButton:
          type: string
          description: "Etichetta del pulsante di pagamento (ad es. il nome del provider di pagamento)."
          pattern: "^[a-zA-Z0-9 ]{1,15}$"
          minLength: 1
          maxLength: 15
          example: "Banca1"
        originId:
          type: string
          description: "ID of the original message"
          pattern: "^[ -~]{24,36}$"
          minLength: 24
          maxLength: 36
          example: "XRUZ-GZAJ-ZUEJ-202407-W-1"

    Error:
      description: Error details
      type: object
      additionalProperties: false
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        description:
          $ref: '#/components/schemas/ErrorDescription'
      required:
        - code
        - description
      example:
        code: "001000001"
        description: "Generic error"

    ErrorCode:
      description: Error code
      type: string
      pattern: "^[A-F0-9]{9}$"
      minLength: 9
      maxLength: 9
      example: "001000001"

    ErrorDescription:
      description: Error description
      type: string
      pattern: "^[ -~]{1,256}$"
      minLength: 1
      maxLength: 256
      example: "Unexpected error from server"

    Errors:
      description: List of errors
      type: object
      additionalProperties: false
      properties:
        errors:
          type: array
          minItems: 1
          maxItems: 32
          items:
            $ref: '#/components/schemas/Error'
      required:
        - errors
      example:
        errors:
          - code: "00000000A"
            description: "Generic error"
          - code: "001000001"
            description: "Unexpected error from server"
    Outcome:
      description: Outcome of submit operation
      type: string
      enum:
        - OK
        - NO_CHANNELS_ENABLED
      example: "OK"

    AccessControlAllowOrigin:
      description: Indicates whether the response can be shared with requesting code from the given origin
      type: string
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048

    RateLimitLimit:
      description: The number of allowed requests in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    RateLimitReset:
      description: The number of seconds left in the current period
      type: integer
      format: int32
      minimum: 1
      maximum: 60

    RetryAfter:
      description: The number of seconds to wait before allowing a follow-up request
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    SendMessageRequest:
      type: object
      properties:
        messageId:
          description: Unique ID of the message
          type: string
          pattern: "^[ -~]{24,64}$"
          minLength: 24
          maxLength: 64
        recipientId:
          description: ID of the recipient
          type: string
          pattern: "^[ -~]{8,64}$"
          minLength: 8
          maxLength: 64
          x-field-extra-annotation: "@lombok.ToString.Exclude"
        triggerDateTime:
          description: When (date and time) the subject who originated the message requested to send it
          type: string
          format: date-time
          minLength: 19
          maxLength: 19
        senderDescription:
          description: Description of the subject who originated the message
          type: string
          pattern: "^[ -~]{1,50}$"
          minLength: 1
          maxLength: 50
        messageUrl:
          description: URL to retrieve the original message
          type: string
          format: uri
          pattern: "^[ -~]{1,2048}$"
          minLength: 1
          maxLength: 2048
        originId:
          description: ID of the original message
          type: string
          pattern: "^[ -~]{24,36}$"
          minLength: 24
          maxLength: 36
        content:
          description: Content of the message
          type: string
          pattern: "^[ -~]{1,140}$"
          minLength: 1
          maxLength: 140
        notes:
          description: Content of the message
          type: string
          pattern: "^[ -~]{1,}$"
          minLength: 1
          maxLength: 100000
        associatedPayment:
          description: Associated Payment flag
          type: boolean
        channel:
          description: channel where the message comes from
          type: string
          enum:
            - SEND
      required:
        - messageId
        - recipientId
        - content
        - triggerDateTime
        - senderDescription
        - messageUrl
        - originId
      example:
        messageId: "8a32fa8a-5036-4b39-8f2e-47d3a6d23f9e"
        recipientId: "RSSMRA85T10A562S"
        triggerDateTime: "2024-06-21T12:34:56"
        senderDescription: "Comune di Pontecagnano"
        messageUrl: "http://wwww.google.it"
        originId: "XRUZ-GZAJ-ZUEJ-202407-W-1"
        content: "Nuovo messaggio!"
        associatedPayment: true
        channel: SEND

    UUID:
      description: UUID
      type: string
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      minLength: 36
      maxLength: 36
      example: "d0d654e6-97da-4848-b568-99fedccb642b"

  requestBodies:
    SendMessage:
      description: Request to send a message
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendMessageRequest'

  parameters:
    RequestId:
      name: RequestId
      in: header
      description: Request ID that will be logged by the service
      required: true
      schema:
        $ref: '#/components/schemas/UUID'

  responses:
    Error:
      description: Error response
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Retry-After:
          description: The number of seconds to wait before allowing a follow-up request
          required: false
          schema:
            $ref: '#/components/schemas/RetryAfter'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'

    SendMessageResponse:
      description: Response to send message request when it is accepted
      headers:
        Access-Control-Allow-Origin:
          description: Indicates whether the response can be shared with requesting code from the given origin
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Retry-After:
          description: The number of seconds to wait before allowing a follow-up request
          required: false
          schema:
            $ref: '#/components/schemas/RetryAfter'
      content:
        application/json:
          schema:
            type: object
            properties:
              outcome:
                $ref: '#/components/schemas/Outcome'
#          schema:
#            type: string
#            example: "Message accepted"

  # ============================================================================
  # Security schemes.
  # ============================================================================
  securitySchemes:
    bearerAuth:
      description: A bearer token in the format of a JWS and conforms to the specifications included in RFC8725
      type: http
      scheme: bearer
      bearerFormat: JWT